import { PathologyParam } from './types';

export const SAMPLE_DATA: PathologyParam[] = [
  {
    id: 1,
    parameterName: 'Creatine Phosphokinase-MM',
    unit: 'U/L',
    criticalLow: 20.0,
    criticalHigh: 500.0,
    isCalculated: false,
    resultType: 'NUMERIC',
    branchId: 1,
    referenceRanges: [
      { gender: 'MALE', ageMin: 1, ageMax: 120, minValue: 39.0, maxValue: 308.0, unit: 'U/L' },
      { gender: 'FEMALE', ageMin: 1, ageMax: 120, minValue: 26.0, maxValue: 192.0, unit: 'U/L' },
    ],
    parameters: [],
  },
  {
    id: 2,
    parameterName: 'Hepatitis A virus IgG',
    unit: '',
    criticalLow: 0,
    criticalHigh: 0,
    isCalculated: false,
    resultType: 'TEXT',
    branchId: 1,
    referenceRanges: [],
    parameters: [],
  },
  {
    id: 3,
    parameterName: 'Hepatitis A virus IgM',
    unit: '',
    criticalLow: 0,
    criticalHigh: 0,
    isCalculated: false,
    resultType: 'TEXT',
    branchId: 1,
    referenceRanges: [],
    parameters: [],
  },
  {
    id: 4,
    parameterName: 'Maternal Screening - Quadruple Marker',
    unit: '',
    criticalLow: 0,
    criticalHigh: 0,
    isCalculated: false,
    resultType: 'TEXT',
    branchId: 1,
    referenceRanges: [],
    parameters: [],
  },
  {
    id: 5,
    parameterName: 'Haemoglobin A',
    unit: '%',
    criticalLow: 4.0,
    criticalHigh: 15.0,
    isCalculated: false,
    resultType: 'NUMERIC',
    branchId: 1,
    referenceRanges: [],
    parameters: [],
  },
];
